routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Content Management System
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
route::resource('users', 'UserController');
route::resource('career_guidance_users', 'CareerGuidanceUserController')->middleware('cekadmin');
route::resource('career_guidances', 'CareerGuidanceController')->middleware('cekadmin');
route::resource('career_guidance_alumnis', 'CareerGuidanceAlumniController');
route::resource('career_guidance_schedules', 'CareerGuidanceScheduleController')->middleware('cekadmin');
route::resource('job_vacancies', 'JobVacancyController')->middleware('cekadmin');
route::resource('job_vacancy_categories', 'JobVacancyCategoryController')->middleware('cekadmin');
route::resource('internships', 'InternshipController')->middleware('cekadmin');
route::resource('internship_categories', 'InternshipCategoryController')->middleware('cekadmin');
route::resource('events', 'EventController')->middleware('cekadmin');
route::resource('event_categories', 'EventCategoryController')->middleware('cekadmin');
route::resource('trainings', 'TrainingController')->middleware('cekadmin');
route::resource('training_categories', 'TrainingCategoryController')->middleware('cekadmin');
Route::put('/change_password/{id}', 'UserController@changePassword')->name('change_password');
Route::put('/close_career_guidance/{id}', 'CareerGuidanceController@closeCareerGuidance')->name('close_career_guidance');
Route::put('/close_career_guidance_alumni/{id}', 'CareerGuidanceAlumniController@closeCareerGuidance')->name('close_career_guidance_alumni');

//User Views
Route::resource('bimbingan-karir', 'BimbinganKarirController');
Route::resource('lowongan-kerja', 'LowonganKerjaController');
Route::resource('magang', 'MagangController');
Route::resource('acara', 'AcaraController');
Route::resource('pelatihan', 'PelatihanController');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/JobVacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobVacancy extends Model
{
    protected $fillable = [
        'author_id', 'category_id', 'judul', 'thumbnail', 'deskripsi', 'slug', 'status'
    ];

    public function category(){
        return $this->belongsTo(JobVacancyCategory::class, 'category_id');
    }

    public function author(){
        return $this->belongsTo(User::class, 'author_id');
    }
}

app/Http/Controllers/JobVacancyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\JobVacancy;
use App\JobVacancyCategory;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class JobVacancyController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $data['job_vacancies'] = JobVacancy::all();
        return view('back.job_vacancies.index', $data);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['job_vacancy_categories'] = JobVacancyCategory::all();
        return view('back.job_vacancies.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required|max:255',
            'thumbnail' => 'required|mimes:jpg,jpeg,png,gif',
            'deskripsi' => 'required',
            'category_id' => 'required',
            'status' => 'required'
        ]);

        $path = ($request->thumbnail)
        ? $request->file('thumbnail')->store("/public/input/lowongan_kerja")
        : null;

        $lowongan_kerja = new JobVacancy([
            'author_id' => Auth::user()->id,
            'judul' => $request->get('judul'),
            'slug' => Str::slug($request->get('judul')),
            'thumbnail' => $path,
            'deskripsi' => $request->get('deskripsi'),
            'category_id' => $request->get('category_id'),
            'status' => $request->get('status'),
        ]);

        $lowongan_kerja->save();
        return redirect('/job_vacancies')->with('success', 'Lowongan Kerja berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['detail'] = JobVacancy::findOrFail($id);
        $data['job_vacancy_categories'] = JobVacancyCategory::all();
        return view('back.job_vacancies.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required|max:255',
            'thumbnail' => 'mimes:jpg,jpeg,png,gif',
            'deskripsi' => 'required',
            'category_id' => 'required',
            'status' => 'required'
        ]);
        
        $lowongan_kerja = JobVacancy::findOrFail($id);
        $path = ($request->thumbnail)
        ? $request->file('thumbnail')->store("/public/input/lowongan_kerja")
        : null;


        if ($request->thumbnail) {
            Storage::delete($lowongan_kerja->thumbnail);
            $lowongan_kerja->thumbnail = $path;
        }

        $lowongan_kerja->judul =  $request->get('judul');
        $lowongan_kerja->slug = Str::slug($request->get('slug'));
        $lowongan_kerja->deskripsi = $request->get('deskripsi');
        $lowongan_kerja->category_id = $request->get('category_id');
        $lowongan_kerja->status = $request->get('status');
        $lowongan_kerja->save();

        return redirect('/job_vacancies')->with('success', 'Lowongan Kerja berhasil diperbaharui!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lowongan_kerja = JobVacancy::findOrFail($id);
        if ($lowongan_kerja->thumbnail) {
            Storage::delete($lowongan_kerja->thumbnail);
        }
        if ($lowongan_kerja->delete()) {
            return redirect('/job_vacancies')->with('success', 'Lowongan Kerja berhasil dihapus!');
        }else{
            return redirect('/job_vacancies')->with('error', 'Lowongan Kerja gagal dihapus!');
        }
    }
}

resources/views/back/job_vacancies/add.blade.php
@extends('back')
@section('title')
    Tambah Lowongan Kerja
@endsection
@section('css')
<link href="{{asset('assets/back/vendors/select2/select2.css')}}" rel="stylesheet">
<link href="{{asset('assets/back/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css')}}" rel="stylesheet">
@endsection
@section('js')
<script src="{{asset('assets/back/vendors/select2/select2.min.js')}}"></script>
<script src="{{asset('assets/back/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('assets/back/vendors/quill/quill.min.js')}}"></script>
<script src="{{asset('assets/back/js/pages/form-elements.js')}}"></script>
<script src="{{ asset('ckeditor.js')}}"></script>
<script>CKEDITOR.replace( 'article-ckeditor', {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
});</script>
<script>
        function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#thumbnail-preview').attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#thumbnail").change(function(){
        readURL(this);
    });
</script>
@endsection
@section('content')
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="dashboard" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="{{url('job_vacancies')}}">Lowongan Kerja</a>
                <span class="breadcrumb-item active">Tambah</span>
            </nav>
        </div>
    </div>
    <div class="card col-md-8">
        <div class="card-body ">
            <h4>Tambah Lowongan Kerja</h4>
            <div class="m-t-25">
                <form action="{{route('job_vacancies.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Judul<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <input type="text" class="form-control m-b-15 @error('judul') is-invalid @enderror" name="judul" value="{{old('judul')}}" placeholder="Judul">
                        @error('judul')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Thumbnail<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <br>
                        <img src="{{asset('images/no_image_available.png')}}" id="thumbnail-preview" class="mt-1 mb-2" alt="" width="350px" height="240px" style="object-fit:cover;">
                        <br>
                        <small>Image 350px*240px</small>
                        <input type="file" class="form-control m-b-15 @error('thumbnail') is-invalid @enderror" id="thumbnail" name="thumbnail" value="{{old('thumbnail')}}" placeholder="Thumbnail">
                        @error('thumbnail')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Isi<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <textarea name="deskripsi" class="form-control m-b-15 @error('deskripsi') is-invalid @enderror" id="article-ckeditor" cols="30" rows="10">{{old('deskripsi')}}</textarea>
                        <br>
                        @error('deskripsi')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Kategori<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <select name="category_id" class="form-control m-b-15 @error('category_id') is-invalid @enderror" id="">
                            <option value="">Pilih Kategori</option>
                            @foreach ($job_vacancy_categories as $item)
                                <option value="{{$item->id}}">{{$item->nama}}</option>
                            @endforeach
                        </select>
                        @error('category_id')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Status<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <select name="status" class="form-control m-b-15 @error('status') is-invalid @enderror" id="">
                            <option value="">Pilih Status</option>
                            <option value="Publish">Publish</option>
                            <option value="Unpublish">Unpublish</option>
                        </select>
                        @error('status')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <button type="submit" class="btn btn-primary btn-md" title="Tambah Lowongan Kerja"><i class="fas fa-plus-circle"></i> Submit</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/back/job_vacancies/edit.blade.php
@extends('back')
@section('title')
    Ubah Lowongan Kerja
@endsection
@section('css')
<link href="{{asset('assets/back/vendors/select2/select2.css')}}" rel="stylesheet">
<link href="{{asset('assets/back/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css')}}" rel="stylesheet">
@endsection
@section('js')
<script src="{{asset('assets/back/vendors/select2/select2.min.js')}}"></script>
<script src="{{asset('assets/back/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('assets/back/vendors/quill/quill.min.js')}}"></script>
<script src="{{asset('assets/back/js/pages/form-elements.js')}}"></script>
<script src="{{ asset('ckeditor.js')}}"></script>
<script>CKEDITOR.replace( 'article-ckeditor', {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
});</script>
<script>
        function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#thumbnail-preview').attr('src', e.target.result);
            }
            
            reader.readAsDataURL(input.files[0]);
        }
    }
    
    $("#thumbnail").change(function(){
        readURL(this);
    });
</script>
@endsection
@section('content')
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="dashboard" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <a class="breadcrumb-item" href="{{url('job_vacancies')}}">Lowongan Kerja</a>
                <span class="breadcrumb-item active">Ubah</span>
            </nav>
        </div>
    </div>
    <div class="card col-md-8">
        <div class="card-body ">
            <h4>Ubah Lowongan Kerja</h4>
            <div class="m-t-25">
                <form action="{{route('job_vacancies.update', $detail->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Judul<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <input type="text" class="form-control m-b-15 @error('judul') is-invalid @enderror" name="judul" value="{{$detail->judul??old('judul')}}" placeholder="Judul">
                        @error('judul')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Thumbnail<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <br>
                        <img src="{{Storage::url($detail->thumbnail)}}" id="thumbnail-preview" class="mt-1 mb-2" alt="" width="350px" height="240px" style="object-fit:cover;">
                        <br>
                        <small>Image 350px*240px</small>
                        <input type="file" class="form-control m-b-15 @error('thumbnail') is-invalid @enderror" id="thumbnail" name="thumbnail"  placeholder="Thumbnail">
                        @error('thumbnail')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Isi<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <textarea name="deskripsi" class="form-control m-b-15 @error('deskripsi') is-invalid @enderror" id="article-ckeditor" cols="30" rows="10">{{$detail->deskripsi??old('deskripsi')}}</textarea>
                        <br>
                        @error('deskripsi')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Kategori<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <select name="category_id" class="form-control m-b-15 @error('category_id') is-invalid @enderror" id="">
                            <option value="">Pilih Kategori</option>
                            @foreach ($job_vacancy_categories as $item)
                                <option value="{{$item->id}}" {{($item->id == $detail->category_id) ? 'selected' : null}}>{{$item->nama}}</option>
                            @endforeach
                        </select>
                        @error('deskripsi')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="">Status<sup title="Wajib diisi" style="color:red;cursor:pointer;">*</sup></label>
                        <select name="status" class="form-control m-b-15 @error('status') is-invalid @enderror" id="">
                            <option value="">Pilih Status</option>
                            <option value="Publish" {{($detail->status == 'Publish') ? 'selected' : null}}>Publish</option>
                            <option value="Unpublish" {{($detail->status == 'Unpublish') ? 'selected' : null}}>Unpublish</option>
                        </select>
                        @error('status')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <button type="submit" class="btn btn-primary btn-md" title="Perbaharui Lowongan Kerja"><i class="fas fa-plus-circle"></i> Submit</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/back/job_vacancies/index.blade.php
@extends('back')
@section('title')
    Lowongan Kerja - Pusat Karir STMIK Sumedang
@endsection
@section('css')
<link href="{{asset('assets/back/vendors/datatables/dataTables.bootstrap.min.css')}}" rel="stylesheet">
@endsection
@section('js')
<script src="{{asset('assets/back/vendors/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/back/vendors/datatables/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/back/js/pages/dashboard-project.j')}}s"></script>
<script>
$('#data-table').DataTable();
</script>
@endsection
@section('content')
<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">Lowongan Kerja</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
                <span class="breadcrumb-item active">Lowongan Kerja</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h4>Daftar Lowongan Kerja</h4>
            @if ($msg = Session::get('success'))
                <div class="alert alert-success">
                    {{$msg}}
                </div>
            @endif
            @if ($msg = Session::get('error'))
                <div class="alert alert-danger">
                    {{$msg}}
                </div>
            @endif
            <a href="job_vacancies/create" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Tambah Data</a>
            <div class="m-t-25">
                <table id="data-table" class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Judul</th>
                            <th>Kategori</th>
                            <th>Pembuat</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($job_vacancies as $i)
                            <tr>
                                <td>
                                    <img src="{{Storage::url($i->thumbnail)}}" width="200" height="120" style="object-fit:cover;" alt="">
                                </td>
                                <td>
                                    <a href="{{route('lowongan-kerja.show', $i->slug)}}">{{$i->judul}}</a> 
                                </td>
                                <td>{{$i->category->nama}}</td>
                                <td>{{$i->author->fullname}}</td>
                                <td>
                                    <a href="{{ route('job_vacancies.edit', $i->id) }}" class="btn btn-rounded btn-info btn-xs"><i class="anticon anticon-edit"></i> Edit</a>
                                    <form action="{{ route('job_vacancies.destroy', $i->id) }}" method="post"
                                        onsubmit="return confirm('Yakin hapus data ini?')">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-rounded btn-danger btn-xs" style="margin: 5px auto;">
                                            <i class="anticon anticon-delete"></i> Hapus</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection