routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Content Management System
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
route::resource('users', 'UserController');
route::resource('career_guidance_users', 'CareerGuidanceUserController')->middleware('cekadmin');
route::resource('career_guidances', 'CareerGuidanceController')->middleware('cekadmin');
route::resource('career_guidance_alumnis', 'CareerGuidanceAlumniController');
route::resource('career_guidance_schedules', 'CareerGuidanceScheduleController')->middleware('cekadmin');
route::resource('job_vacancies', 'JobVacancyController')->middleware('cekadmin');
route::resource('job_vacancy_categories', 'JobVacancyCategoryController')->middleware('cekadmin');
route::resource('internships', 'InternshipController')->middleware('cekadmin');
route::resource('internship_categories', 'InternshipCategoryController')->middleware('cekadmin');
route::resource('events', 'EventController')->middleware('cekadmin');
route::resource('event_categories', 'EventCategoryController')->middleware('cekadmin');
route::resource('trainings', 'TrainingController')->middleware('cekadmin');
route::resource('training_categories', 'TrainingCategoryController')->middleware('cekadmin');
Route::put('/change_password/{id}', 'UserController@changePassword')->name('change_password');
Route::put('/close_career_guidance/{id}', 'CareerGuidanceController@closeCareerGuidance')->name('close_career_guidance');
Route::put('/close_career_guidance_alumni/{id}', 'CareerGuidanceAlumniController@closeCareerGuidance')->name('close_career_guidance_alumni');

//User Views
Route::resource('bimbingan-karir', 'BimbinganKarirController');
Route::resource('lowongan-kerja', 'LowonganKerjaController');
Route::resource('magang', 'MagangController');
Route::resource('acara', 'AcaraController');
Route::resource('pelatihan', 'PelatihanController');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/MagangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Internship;

class MagangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['internships'] = Internship::paginate(6);
        return view('magang.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $data['detail'] = Internship::where('slug',$slug)->first();
        return view('magang.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/magang/detail.blade.php
@extends('layouts.app')
@section('title')
    {{$detail->judul}}
@endsection
@section('content')
<section class="padding-100-0 position-relative">
    <div class="body_overlay_ono"></div>
    <div class="container">
        <div class="col-md-12 help-center-header ">
            <h2 class="help-center-title">{{$detail->judul}}</h2>
            <small>Artikel ini dibuat <i>{{date("F j, Y H:i", strtotime($detail->created_at))}}</i>  oleh <b>{{$detail->author->fullname}}</b> </small>
            <p> 
                {!! $detail->deskripsi !!}
            </p>
            <small>Kategori: <a href="#">{{$detail->category->nama}}</a> </small>
        </div>

    </div>
</section>

@endsection

resources/views/magang/index.blade.php
@extends('layouts.app')
@section('title')
    Magang
@endsection
@section('bg-image')
 style="background: url('assets/front/media/magang.jpeg') no-repeat;width:100%;background-size:cover;"
@endsection
@section('content')
<section class="white-bg">
	<div class="container">
        <div class="row justify-content-start blog-items-home"><!-- start row -->
                @if ($internships->isEmpty())
                    <h1>Belum ada data</h1>
                    <br><br>
                @endif
                @foreach ($internships as $item)
                    <div class="col-md-4 "><!-- col -->
                        <div class="home-blog-te shadow p-3 mb-5 bg-body rounded"><!-- blog container -->
                            <div class="post-thumbn parallax-window" style="background: url({{url(Storage::url($item->thumbnail))}}) no-repeat center;"></div><!-- post thumbnail -->
                            <div class="post-bodyn">
                                <h5><a href="{{route('magang.show', $item->slug)}}">{{$item->judul}}</a></h5><!-- post title -->
                                <p><i class="far fa-calendar"></i>{{date("F j, Y", strtotime($item->created_at))}}</p><!-- post date -->
                            </div>
                        </div><!-- end blog container -->
                    </div><!-- end col -->
                @endforeach
            </div>	
        </div>
	</section>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {{$internships->links()}}
        </nav>
@endsection