routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Content Management System
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
route::resource('users', 'UserController');
route::resource('career_guidance_users', 'CareerGuidanceUserController')->middleware('cekadmin');
route::resource('career_guidances', 'CareerGuidanceController')->middleware('cekadmin');
route::resource('career_guidance_alumnis', 'CareerGuidanceAlumniController');
route::resource('career_guidance_schedules', 'CareerGuidanceScheduleController')->middleware('cekadmin');
route::resource('job_vacancies', 'JobVacancyController')->middleware('cekadmin');
route::resource('job_vacancy_categories', 'JobVacancyCategoryController')->middleware('cekadmin');
route::resource('internships', 'InternshipController')->middleware('cekadmin');
route::resource('internship_categories', 'InternshipCategoryController')->middleware('cekadmin');
route::resource('events', 'EventController')->middleware('cekadmin');
route::resource('event_categories', 'EventCategoryController')->middleware('cekadmin');
route::resource('trainings', 'TrainingController')->middleware('cekadmin');
route::resource('training_categories', 'TrainingCategoryController')->middleware('cekadmin');
Route::put('/change_password/{id}', 'UserController@changePassword')->name('change_password');
Route::put('/close_career_guidance/{id}', 'CareerGuidanceController@closeCareerGuidance')->name('close_career_guidance');
Route::put('/close_career_guidance_alumni/{id}', 'CareerGuidanceAlumniController@closeCareerGuidance')->name('close_career_guidance_alumni');

//User Views
Route::resource('bimbingan-karir', 'BimbinganKarirController');
Route::resource('lowongan-kerja', 'LowonganKerjaController');
Route::resource('magang', 'MagangController');
Route::resource('acara', 'AcaraController');
Route::resource('pelatihan', 'PelatihanController');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/LowonganKerjaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\JobVacancy;
use DataTables;
use Illuminate\Support\Carbon;

class LowonganKerjaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // $data['job_vacancies'] = JobVacancy::paginate(6);
        // return view('lowongan_kerja.index', $data);
        Carbon::setLocale('id');
        if ($request->ajax()) {
            $data = JobVacancy::select('*');
            return Datatables::of($data)
            ->addIndexColumn()
                    ->editColumn('judul', function ($row) {
                        $judul = '<a href="'.url('lowongan-kerja/'.$row->slug).'">'.$row->judul.'</a>';
                            return $judul;
                    })
                    ->rawColumns(['judul'])
                    ->editColumn('created_at', function ($request) {
                        return date("F j, Y", strtotime($request->created_at));
                    })
                    ->make(true);
        }
        return view('lowongan_kerja.index');
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $data['detail'] = JobVacancy::where('slug',$slug)->first();
        return view('lowongan_kerja.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/lowongan_kerja/detail.blade.php
@extends('layouts.app')
@section('title')
    {{$detail->judul}}
@endsection
@section('content')
<section class="padding-100-0 position-relative">
    <div class="body_overlay_ono"></div>
    <div class="container">
        <div class="col-md-12 help-center-header ">
            <h2 class="help-center-title">{{$detail->judul}}</h2>
            <small>Artikel ini dibuat <i>{{date("F j, Y H:i", strtotime($detail->created_at))}}</i>  oleh <b>{{$detail->author->fullname}}</b> </small>
            <p> 
                {!! $detail->deskripsi !!}
            </p>
            <small>Kategori: <a href="#">{{$detail->category->nama}}</a> </small>
        </div>

    </div>
</section>

@endsection

resources/views/lowongan_kerja/index.blade.php
@extends('layouts.app')
@section('title')
    Lowongan Kerja
@endsection
@section('bg-image')
 style="background: url('assets/front/media/loker.jpeg') no-repeat;width:100%;background-size:cover;object-fit:cover"
@endsection
@section('css')

<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endsection
@section('content')
<section class="white-bg">
	<div class="container">
        <div class="row justify-content-center blog-items-home"><!-- start row -->
                <table class="table-responsive data-table" style="width: 100%">
                    <thead>
                        <tr>
                            <th>Judul</th>
                            <th>Tanggal Rilis</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>	
        </div>
	</section>
    <br>
@endsection
@section('js')

<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(function () {
      var table = $('.data-table').DataTable({
          processing: true,
          serverSide: true,
          pageLength: 100,
          bInfo: false,
          responsive: true,
          ajax: "{{ route('lowongan-kerja.index') }}",
          columns: [
              {data: 'judul', name: 'judul'},
              {data: 'created_at', name: 'created_at'},
              {
                data: 'status', 
                name: 'status',
                render: function (data) {
                    if (data !== null) {
                        if (data === "Publish") {
                            return "<span class='badge badge-success'>Tersedia</span>";
                        } else {
                            return "<span class='badge badge-danger'>Tutup</span>";
                        }
                    } else {
                    return "Belum terdaftar";
                    }
                }
            },
          ]
      });
    });
  </script>
@endsection